### ISSUE TITLE
Issue on output.txt

### ISSUE THREAD

**Issue by amalanwar** [federico-terzi/gesture-keyboard#10]
Hai,
We tried doing the way you told us. But the file doesn't update the contents automatically. To see the modified file we need to open and close the file each time, also when the command 'Enable_ write=true'  is run  it auto predicts the word "aboveeee".
Can you briefly explain the use of pygarl your new library? Is it more accurate?

**Comment by nikir** [comment]
Hey, @amalanwar do one thing just run the windows.py, when you are running the project. it is a GUI for the project it will show you output. You don't have open the output.txt file again and again.

**Comment by amalanwar** [comment]
Hey,
Thanks federico, Now it works perfectly  fine..😄

**Comment by federico-terzi** [comment]
You're welcome :)
