### ISSUE TITLE
gesture keboard

### ISSUE THREAD

**Issue by harikrishnareddy1997** [federico-terzi/gesture-keyboard#13]
thnx brooo am successfully done with this project ....but for me baudrate is 9600.....an nice code broo......i

**Comment by federico-terzi** [comment]
You're welcome :)

**Comment by harikrishnareddy1997** [comment]
federico-terzi closed this issue means what??  Broo

**Comment by federico-terzi** [comment]
What is the problem? I can't understand your question

**Comment by harikrishnareddy1997** [comment]
Y did i get message like closed #13 this my qs  Mr.federico bro

**Comment by federico-terzi** [comment]
It means that the question has been answered.
