### ISSUE TITLE
how to predict words Instead of characters

### ISSUE THREAD

**Issue by MaheshChandra97** [federico-terzi/gesture-keyboard#20]
Hello sir ,I have implemented your project.It is working fine with mpu6050 (6 axis),but when I tried to implement with both mpu6050 and flex sensors or (only flex sensors) its performance has been decreased and it is not predicting well.

Also can we predict words instead of characters .

**Comment by MaheshChandra97** [comment]
Please reply ...

**Comment by federico-terzi** [comment]
Hi,

I've never used flex sensors so I don't know much about them. The only suggestion I can give you is to experiment with the parameters of the classifier.
With whole words the recognition is much harder, you would have to train the classifier to recognize every possible word...

Best regards

**Comment by MaheshChandra97** [comment]
Thank you

But how we give words and how we train them.For characters,you have converted them into ascii and again from ascii to predicted char ,but how we test words.
Please give me some suggestions regarding this.

**Comment by MaheshChandra97** [comment]
Please help me out of this.
