### ISSUE TITLE
Bluetooth not working

### ISSUE THREAD

**Issue by gijovarughese** [federico-terzi/gesture-keyboard#21]
Hi. Thank you for your project. I can successfully predict the characters using usb. But I can't seem to get any data from the Bluetooth module. Is there any way to check if the Bluetooth module is sending data to the pc? There is no output in the serial monitor when I try Bluetooth mode. Any thoughts?

**Comment by federico-terzi** [comment]
Hi,
The first thing you should do is to check out if you see any output using the arduino ide serial monitor using the bluetooth serial port

**Comment by gijovarughese** [comment]
Hey,
Thank you for your response. So in the ide I must change from the Arduino port to the receiving port of Bluetooth right? Then if I don't get any output on serial monitor it's a faulty Bluetooth module?

**Comment by federico-terzi** [comment]
You're welcome. Not necessarily, it could also be related to a wrong connection

**Comment by gijovarughese** [comment]
Thank you. And I'm using a hc05 instead of hc06. It doesn't make a difference right?

**Comment by gijovarughese** [comment]
Thank you I'm getting output on the serial monitor and the prediction. But I had to change the baud rate from 38400 to 9600 in the Arduino file for bluetooth.start(). Is there any problem if I do this? I seem to get

**Comment by gijovarughese** [comment]
Thank you I'm able to get the Bluetooth working also. But it seems like I must keep uploading the Arduino code to the pro micro every time I plug it in again. If I don't upload the sketch, it keeps predicting d for every movement. How can I make the code stay on the board?
