### ISSUE TITLE
Bluetooth transmit successful, cannot be read with record function

### ISSUE THREAD

**Issue by Bryan-Tam** [federico-terzi/gesture-keyboard#23]
As the title suggests, I can see bluetooth data being transmitted via the bluetooth port. When running the record function however, this data is not passed properly and it does not record at all. I am not sure why the record function cannot interpret this bluetooth data.

**Comment by federico-terzi** [comment]
Have you changed the SERIAL_PORT accordingly?

**Comment by Bryan-Tam** [comment]
Do you mean the SERIAL_PORT in the record script?
