### ISSUE TITLE
Continuous Data Prediction w/o using a Button

### ISSUE THREAD

**Issue by snow-drop** [federico-terzi/gesture-keyboard#25]
Good day and good work on sharing this project! I would like to ask if it is possible to predict the data continuously without using a button to trigger the sending of data from the device to the computer. Thanks!

**Comment by federico-terzi** [comment]
HI @snow-drop,
Unfortunately, for continuous recognition, the problem is much harder to tackle. You could make some experimentations. but I'm currently not able to help you out with this issue.

Best regards

**Comment by snow-drop** [comment]
@federico-terzi It's ok, thank you for your response. I'm still researching on how to do it as I'm still newbie in terms of machine learning :) Glad I could start learning practical machine learning with this. Thanks again! :)
