### ISSUE TITLE
Using Arduino nano instead of micro

### ISSUE THREAD

**Issue by Nadamohame** [federico-terzi/gesture-keyboard#27]
Great project by the way really inspired from it. I am using arduino nano for this project but its not working can you please tell me what I am supposed to change for it to work and how to connect it ?
Thanks

**Comment by federico-terzi** [comment]
Hi @Nadamohame, thanks for the kind words. It should be working correctly as long as you connect it to the right pins. Unfortunately, I'm very busy with my exams right now and I can't offer much help
