### ISSUE TITLE
TypeError: a bytes-like object is required, not str

### ISSUE THREAD

**Issue by Nadamohame** [federico-terzi/gesture-keyboard#29]
![IMG_20191119_205935](https://user-images.githubusercontent.com/48436185/69177404-21a40100-0b10-11ea-9f56-8d4f9c25733e.jpg)
After preforming pygarl sprint - p myserialport in command prompt 
This error type appears and I don't know why please help me need to fix it so bad for my project

**Comment by ishanshah001** [comment]
even i am getting the same error. It would be great if someone can help.

**Comment by ishanshah001** [comment]
hi. use python 2 instead of python 3.
