### ISSUE TITLE
can't run start.py

### ISSUE THREAD

**Issue by viralcoder** [federico-terzi/gesture-keyboard#3]
I uploaded program to arduino and changed the port in start.py and run the command 
python start.py target=a:0 port=COM3 but I am getting these errors. Please help me

Traceback (most recent call last):
  File "start.py", line 118, in <module>
    ser = serial.Serial(SERIAL_PORT, BAUD_RATE, timeout = TIMEOUT)
  File "C:\Python27\lib\site-packages\serial\serialwin32.py", line 38, in __init__
    SerialBase.__init__(self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\serial\serialutil.py", line 282, in __init__
    self.open()
  File "C:\Python27\lib\site-packages\serial\serialwin32.py", line 66, in open
    raise SerialException("could not open port %r: %r" % (self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM3': WindowsError(5, 'Access is denied.')

**Comment by federico-terzi** [comment]
Probably the error is caused by:
* Access permissions: try to run the terminal with admin rights, and it should solve the problem.
* Invalid serial port: are you sure COM3 is a valid port?

**Comment by viralcoder** [comment]
Sir Federico Terzi,
When I just press and release the push button it predicts "a" or make any random gesture rather than an alphabet it predicts a random value. How can this be solved?
And one more things how can I get these alphabets printed on Notepad or Word?
