### ISSUE TITLE
issue with start.py

### ISSUE THREAD

**Issue by nikir** [federico-terzi/gesture-keyboard#4]
when I run the start.py it creates 3 new file output.txt, compiled form of signals and suggestion file....but nothing happens. how do I know that new data set is creating?

**Comment by federico-terzi** [comment]
Do you have a connected Arduino sending motion data?

**Comment by nikir** [comment]
yes..arduino is connected and i not using bluetooth module right now
![screenshot 49](https://user-images.githubusercontent.com/14983868/36094317-bbd18602-1013-11e8-8048-9f99394dec1d.png)
@federico-terzi 
and that yellow led is not working when i press the button. i am using the basic script of arduino without bluetooth one.
how much resistance did u use with leds?

**Comment by nikir** [comment]
could please tell why is this coming. i have only record data for A only. but i am not able to train the model is error is coming
![screenshot 50](https://user-images.githubusercontent.com/14983868/36141432-b2b91672-10ca-11e8-884e-fe4c0512415b.png)

**Comment by federico-terzi** [comment]
I need to see the serial output of the Arduino to determine if it is correct.
So please run the Arduino IDE, open the serial monitor and try the device with it.
Then paste the result here.

**Comment by nikir** [comment]
![screenshot 51](https://user-images.githubusercontent.com/14983868/36208359-d17138de-11be-11e8-96f6-ba6996a9646f.png)
![screenshot 52](https://user-images.githubusercontent.com/14983868/36208361-d1c77348-11be-11e8-93e9-f9e52818bb48.png)

**Comment by viralcoder** [comment]
Hey nikir, I am too working on this as a final yr project can you send me where did you interface buttons and LEDs

**Comment by viralcoder** [comment]
Dear federico terzi,
Please create a video demonstrating steps of creating data set.

**Comment by federico-terzi** [comment]
@nikir The output of the device seems correct, unfortunately I can't tell what's wrong.
@viralcoder Right now I'm working on the documentation of my new library, pyGARL, that's much more powerful than the gesture keyboard. It will be available here: https://github.com/federico-terzi/pygarl
With that library, you can create the gesture keyboard in 10 lines of code and has plenty of tools to record a new dataset.
Best Regards

**Comment by nikir** [comment]
@viralcoder send me your e-mail id. nikhilrai42@gmail.com.
