### ISSUE TITLE
Possible hardware for your gesture keyboard

### ISSUE THREAD

**Issue by diedoman** [federico-terzi/gesture-keyboard#5]
Hello federico! I just read about your keyboard in a dutch magazine (linux magazine). Just wanted to let you know that there has been a open-source hardware project, which was using the same accelerosensor, but with a nrf51822 bluetooth chip on the board instead of the arduino. Might be nice to look into if you're considering to produce hardware for the keyboard yourself!

https://github.com/wemaketotem/health-sensor-aurora-hardware?files=1

Keep up the awesome work!

**Comment by diedoman** [comment]
Also, if you're looking for source code to read from that sensor(with the nrf51822) we were using it in another project and ported all the required stuff to eclipse cdt with a j-link programmer(j-link eudo is about 30 euro's).
https://github.com/Siebren1995/EMES-Cue2Walk
Happy coding!

**Comment by federico-terzi** [comment]
Hi,

Thank you very much for the suggestion, I will surely check it out! :)

Have a nice day,
Federico
