### ISSUE TITLE
I'm using arduino uno but can't get it working...

### ISSUE THREAD

**Issue by ApoorvMengudale** [federico-terzi/gesture-keyboard#6]
Hi federico terzi,

I'm using arduino uno, i was able to run the project with usb cable but its not working with Bluetooth.

**Comment by ApoorvMengudale** [comment]
I'm also using hc-05 do i need to use hc- 06 or Arduino pro micro...

**Comment by federico-terzi** [comment]
Hi,
If it works with the usb cable, that's a good sign. The problem is related to the bluetooth connection.
Did you select the correct bluetooth serial port?
A good way to find out is to check the serial output from the Arduino IDE.
Have a nice day

**Comment by ApoorvMengudale** [comment]
Yes, I have chosen the correct serial port ... But I guess Arduino not transmitting data.

**Comment by federico-terzi** [comment]
Make sure `boolean isBluetoothEnabled = true;` and the bluetooth module is connected to the right pins ( 10 and 16 )

**Comment by ApoorvMengudale** [comment]
![img_20180218_165910](https://user-images.githubusercontent.com/36592025/36351293-7b020fb6-14cd-11e8-97dc-c0f32129ba36.jpg)
Are these right pins brother?

**Comment by ApoorvMengudale** [comment]
federico terzi you there brother ?

**Comment by federico-terzi** [comment]
Hi,

Sorry for the late reply, I'm very busy these days. 
Those pins are not right because the bluetooth module use Software Serial, and not the built in serial interface. You should connect it to 2 ports between 2 and 12 and then change these line with the ones that you chosen:

```// Pins connected to the HC-06 bluetooth module
int rxPin = 10;
int txPin = 16;
SoftwareSerial bluetooth(rxPin, txPin);
```

Also, I never used the HC-05 module, I don't know if there are differences.

**Comment by ApoorvMengudale** [comment]
ok thanks for the reply, will surely try it out.

**Comment by ApoorvMengudale** [comment]
Can you please send me the circuit diagram ?

**Comment by ApoorvMengudale** [comment]
Are you there?

**Comment by federico-terzi** [comment]
This is the circuit of the device.

![circuito_finale_schem](https://user-images.githubusercontent.com/20475953/36746738-599416bc-1bf3-11e8-9f40-a8cc9c7bddba.png)

**Comment by ApoorvMengudale** [comment]
Thanks alot.

**Comment by federico-terzi** [comment]
You're welcome
