### ISSUE TITLE
Regarding the Gesture Keyboard

### ISSUE THREAD

**Issue by IndrajitFED** [federico-terzi/gesture-keyboard#7]
Sir / Bro Thanks for the project 
   I have run the project successfully using serial port but when i **gesture** for **e** it draw **d** and i am using Arduino UNO for this Please help me with this

Brazilian
Eu executei o projeto com sucesso usando a porta serial, mas quando eu ** gesticule ** para ** e ** desenhar ** d ** e estou usando Arduino UNO para isso, por favor me ajude com isso

Please REPLY

**Comment by federico-terzi** [comment]
You should recreate the dataset to match your movement.
