### ISSUE TITLE
Output.txt

### ISSUE THREAD

**Issue by uraniumpotato96** [federico-terzi/gesture-keyboard#8]
Hey man first all thanks for all the files and all, I was able to setup everything and everything is working alright in the command line I'm able to get the prediction also right, but I'm not able to get text on the output.txt. Can I know how to correct that. 

Thanks in advance

**Comment by federico-terzi** [comment]
That's strage, which OS are you using?

**Comment by uraniumpotato96** [comment]
I'm using Windows 10, the prediction algorithm is working on the command
prompt but nothing on the text screen.

**Comment by federico-terzi** [comment]
Make sure to have `ENABLE_WRITE=True` or by passing the "write" parameter in the console.

**Comment by uraniumpotato96** [comment]
Thanks, it works like a charm now!!

**Comment by uraniumpotato96** [comment]
Thanks, it works like a charm now!!

**Comment by IndrajitFED** [comment]
Uraniumpotato96 did you had does u train the machine or u use the same dataset please let me know 

And can u send me your Working Tutorial
My mail is indrajitshinde234@gmail.com

**Comment by uraniumpotato96** [comment]
Delete everything in the data folder and train the machine again, read the code in start.py everything is well commented.

**Comment by uraniumpotato96** [comment]
Hey man one last thing how do you store the space in the datasets??

**Comment by federico-terzi** [comment]
For special characters, you can for example train the algorithm with uppercase letters, assigning to each of them a special meaning. For example, when receiving a "D", the program deletes the last character.
