### ISSUE TITLE
User inteface

### ISSUE THREAD

**Issue by amalanwar** [federico-terzi/gesture-keyboard#9]
Hai,
 The project is really cool, The predicting part is working in the command prompt,now can you tell me how to display it on a screen simultaneously like shown in your video.

**Comment by federico-terzi** [comment]
When a new prediction is made, the program saves it in the output.txt file. I made a very simple program that reads that file continuosly. 
Make sure to set `ENABLE_WRITE=True` in the start.py module.

**Comment by amalanwar** [comment]
We tried doing that. But the file doesn't update the contents
automatically. To see the modified file we need to open and close the file
each time, also when the command 'Enable_ write=true'  is run  it auto
predicts the word "aboveeee".
Can you briefly explain the use of pygarl your new library? Is it more
accurate?
